id: I34DD116F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-10T08:48:41+00:00'
last_modified: '2022-06-15T14:08:03.496016+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19892
  title: ལུགས་ཀྱི་བསྟན་བཅོས་ལྷ་དང་དཔལ་འདུ་བའི་ནོར་བུ་སོགས་བསླབ་བྱ་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FD94:
      image_group_id: I2PD20541
      title: Volume 1 of lugs kyi bstan bcos lha dang dpal 'du ba'i nor bu sogs bslab
        bya phyogs bsdus/
      total_pages: 64
      order: 1
      base_file: FD94.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
